### ISSUE TITLE
В сберегательном счете, при пополнении не суммируется значение баланса со значением пополнения

### ISSUE THREAD

**Issue by NikitkaGordeev** [ArtemS27/Java_team_diplom#1]
# Описание
При пополнении баланса значение пополнения не суммируется со значением текущего баланса, а заменяет его (текущий баланс) на значение пополнения.

# Локация дефекта
https://github.com/ArtemS27/Java_team_diplom/blob/33867b575c4442a1402cd43726081cee528b2f4d/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L73

# Шаги воспроизведения
1. Открыть [проект](https://github.com/ArtemS27/Java_team_diplom/tree/saving) в IDEA.
2. Перейти в класс [SavingAccountTest](https://github.com/ArtemS27/Java_team_diplom/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java).
3. Заполнить тест _shouldAddLessThanMaxBalance_ значениями:
initialBalance: 2_000;
minBalance: 1_000;
maxBalance: 10_000;
rate: 5; 
4. Пополнить баланс на 3_000 с помощью метода add;
5. Сравнить ожидаемый результат с актуальным запустив тест;

*Ожидаемый результат: Баланс на счете пополнился на 3000 руб. и стал равен 5000 руб.
*Фактический результат: Баланс на счете стал 3000 руб.

# Тест
https://github.com/ArtemS27/Java_team_diplom/blob/7e01d1602ba0e7787782ab0ac6d54e4d04a0db01/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L8-L20

# Скриншот
![image](https://github.com/ArtemS27/Java_team_diplom/assets/130284238/98a5a170-4f5b-4583-a381-7b32f246f6e4)

# Окружение
* **Операционная система:** Windows 10 Version 22H2 x64
* **IDE:**IntelliJ IDEA 2022.3.3 (Community Edition) Build #IC-223.8836.41, built on March 10, 2023
* **Java:** OpenJDK  "19.0.2" 2023-01-17

**Comment by ArtemS27** [comment]
Изменена формула пополнения баланса.
