### ISSUE TITLE
В сберегательном счете округление процента рассчитывается не верно

### ISSUE THREAD

**Issue by NikitkaGordeev** [ArtemS27/Java_team_diplom#10]
# Описание
В сберегательном счете при округлении процента нецелых чисел расчет производится не верно, требуется коррекция формулы расчета.

# Локация дефекта
https://github.com/ArtemS27/Java_team_diplom/blob/7c120f56a14f466be2bbf4b2cb1521cc38a1a067/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L87-L90

# Шаги воспроизведения
1. Открыть [проект](https://github.com/ArtemS27/Java_team_diplom/tree/saving) в IDEA.
2. Перейти в класс [SavingAccountTest](https://github.com/ArtemS27/Java_team_diplom/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java).
3. Заполнить тест _shouldRoundTheBalance_ значениями:
initialBalance: 1_499;
minBalance: 1_000;
maxBalance: 10_000;
rate: 80; 
4. Сравнить ожидаемый результат с актуальным запустив тест;

*Ожидаемый результат: Баланс успешно округлен и составляет 1199 рублей.
*Фактический результат: Баланс округлен неверно, значение баланса составляет 1120 рублей.
# Тест
https://github.com/ArtemS27/Java_team_diplom/blob/d13874c634dab3178f441e2570823b2b88e311a5/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L140-L149

# Скриншот
![image](https://github.com/ArtemS27/Java_team_diplom/assets/130284238/f0f1fd99-9f0f-4d35-b769-f01116698568)

# Окружение
* **Операционная система:** Windows 10 Version 22H2 x64
* **IDE:**IntelliJ IDEA 2022.3.3 (Community Edition) Build #IC-223.8836.41, built on March 10, 2023
* **Java:** OpenJDK  "19.0.2" 2023-01-17

**Comment by ArtemS27** [comment]
Изменена формула расчета на год.
