### ISSUE TITLE
В кредитном счете не суммируется баланс при пополнении счета с положительным балансом.

### ISSUE THREAD

**Issue by ArtemS27** [ArtemS27/Java_team_diplom#11]
# Описание
В кредитном счете при пополнении счета с положительным балансом не суммируется баланс.
# Локация дефекта
https://github.com/ArtemS27/Java_team_diplom/blob/2f340c189e561d9b983284dc6009ba714cd402f3/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L67-L74
# Шаги воспроизведения
1. Открыть [проект](https://github.com/ArtemS27/Java_team_diplom/tree/credit) в IDEA.
2. Перейти в [класс](https://github.com/ArtemS27/Java_team_diplom/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) CreditAccountTest.
3. Заполнить конструктор account в тесте shouldAddToPositiveBalance данными:
initialBalance: 1_000,
creditLimit: 3_000,
rate: 15.
4. Выставить значение переменной amount: 5_000, в методе account.add
5. Запустить тест.
6. Посмотреть на сравнение результатов.

*Ожидаемый результат: Баланс равен 6000.
*Фактический результат: Баланс равен 5000.

# Скриншот
![image](https://github.com/ArtemS27/Java_team_diplom/assets/130216421/74716b5e-6ee0-43bc-8073-cdac2c21752b)

# Окружение
* **Операционная система:** Windows 11 Домашняя 22H2 х64
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition) Build #IC-231.8109.175, built on March 28, 2023
* **Java:** OpenJDK 11.0.18

**Comment by NikitkaGordeev** [comment]
В методе add отредактировано условие: https://github.com/ArtemS27/Java_team_diplom/blob/d765fe49ce0f925649c53913de0f4b8187692ee6/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L72-L72
