### ISSUE TITLE
В кредитном счете не вычитает сумму оплаты при положительном балансе не выходя за лимит.

### ISSUE THREAD

**Issue by ArtemS27** [ArtemS27/Java_team_diplom#13]
# Описание
В кредитном счете при оплате не выходя за лимит при положительном балансе не вычитает сумму оплаты из баланса.
# Локация дефекта
https://github.com/ArtemS27/Java_team_diplom/blob/2f340c189e561d9b983284dc6009ba714cd402f3/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L42-L53
# Шаги воспроизведения
1. Открыть [проект](https://github.com/ArtemS27/Java_team_diplom/tree/credit) в IDEA.
2. Перейти в [класс](https://github.com/ArtemS27/Java_team_diplom/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) CreditAccountTest.
3. Заполнить конструктор account в тесте shouldChargeMoneyWhenPayInLimitPositiveBalance данными:
initialBalance: 1_500,
creditLimit: 5_000,
rate: 15.
4. Выставить значение переменной amount: 500, в методе account.pay
5. Запустить тест.
6. Посмотреть на сравнение результатов.

*Ожидаемый результат: Баланс равен 1000.
*Фактический результат: Баланс равен -500.

# Скриншот
![image](https://github.com/ArtemS27/Java_team_diplom/assets/130216421/dabfd316-7020-48b6-b0a3-e8f8060c5129)

# Окружение
* **Операционная система:** Windows 11 Домашняя 22H2 х64
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition) Build #IC-231.8109.175, built on March 28, 2023
* **Java:** OpenJDK 11.0.18

**Comment by NikitkaGordeev** [comment]
В методе pay отредактировано условие: https://github.com/ArtemS27/Java_team_diplom/blob/d331a4302b45254d0eb3eff5d6e76313085d016e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L50-L51
