### ISSUE TITLE
В кредитном счете вычитает сумму оплаты при отрицательном балансе сверх лимита.

### ISSUE THREAD

**Issue by ArtemS27** [ArtemS27/Java_team_diplom#17]
# Описание
В кредитном счете при оплате сверх лимита при отрицательном балансе вычитает сумму оплаты из баланса.
# Локация дефекта
https://github.com/ArtemS27/Java_team_diplom/blob/2f340c189e561d9b983284dc6009ba714cd402f3/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L42-L53
# Шаги воспроизведения
1. Открыть [проект](https://github.com/ArtemS27/Java_team_diplom/tree/credit) в IDEA.
2. Перейти в [класс](https://github.com/ArtemS27/Java_team_diplom/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) CreditAccountTest.
3. Заполнить конструктор account в тесте shouldNotChargeMoneyWhenPayOverLimitNegativeBalance данными:
initialBalance: -500,
creditLimit: 1_000,
rate: 15.
4. Выставить значение переменной amount: 1_000, в методе account.pay
5. Запустить тест.
6. Посмотреть на сравнение результатов.

*Ожидаемый результат: Баланс равен -500.
*Фактический результат: Баланс равен -1500.

# Скриншот
![image](https://github.com/ArtemS27/Java_team_diplom/assets/130216421/511254f4-80f5-4d27-9855-427403815dcb)

# Окружение
* **Операционная система:** Windows 11 Домашняя 22H2 х64
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition) Build #IC-231.8109.175, built on March 28, 2023
* **Java:** OpenJDK 11.0.18

**Comment by NikitkaGordeev** [comment]
В методе pay отредактировано условие:
https://github.com/ArtemS27/Java_team_diplom/blob/d331a4302b45254d0eb3eff5d6e76313085d016e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46-L48
