### ISSUE TITLE
В кредитном счете происходит списание годового процента при положительном балансе.

### ISSUE THREAD

**Issue by ArtemS27** [ArtemS27/Java_team_diplom#18]
# Описание
Происходит списание годового процента при положительном балансе.
# Локация дефекта
https://github.com/ArtemS27/Java_team_diplom/blob/2f340c189e561d9b983284dc6009ba714cd402f3/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L85-L88
# Шаги воспроизведения
1. Открыть [проект](https://github.com/ArtemS27/Java_team_diplom/tree/credit) в IDEA.
2. Перейти в [класс](https://github.com/ArtemS27/Java_team_diplom/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) CreditAccountTest.
3. Заполнить конструктор account в тесте shouldNotMadeYearChargeIfBalancePositive данными:
initialBalance: 1_000,
creditLimit: 3_000,
rate: 15.
4. Запустить тест.
5. Посмотреть на сравнение результатов.

*Ожидаемый результат: Баланс равен 0.
*Фактический результат: Баланс равен 150.

# Скриншот
![image](https://github.com/ArtemS27/Java_team_diplom/assets/130216421/2e90b729-48d4-47b8-9439-734e91c0fc4d)

# Окружение
* **Операционная система:** Windows 11 Домашняя 22H2 х64
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition) Build #IC-231.8109.175, built on March 28, 2023
* **Java:** OpenJDK 11.0.18

**Comment by NikitkaGordeev** [comment]
В методе yearChange отредактировано условие: https://github.com/ArtemS27/Java_team_diplom/blob/2df79bd950c417d4828bc25dc466e4b5084d37b2/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L90-L96
