### ISSUE TITLE
В кредитном счете не выводит ошибку при вводе отрицательного кредитного лимита.

### ISSUE THREAD

**Issue by ArtemS27** [ArtemS27/Java_team_diplom#19]
# Описание
Не выводит ошибку IlligalArgumentException при вводе отрицательного кредитного лимита.
# Локация дефекта
https://github.com/ArtemS27/Java_team_diplom/blob/2f340c189e561d9b983284dc6009ba714cd402f3/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20-L29
# Шаги воспроизведения
1. Открыть [проект](https://github.com/ArtemS27/Java_team_diplom/tree/credit) в IDEA.
2. Перейти в [класс](https://github.com/ArtemS27/Java_team_diplom/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) CreditAccountTest.
3. Заполнить конструктор account в тесте shouldThrowExceptionWhenCreditLimitISNegative данными:
initialBalance: 0,
creditLimit: -5_000,
rate: 15.
4. Запустить тест.
5. Посмотреть на сравнение результатов.

*Ожидаемый результат: Вывод сообщения: "Кредитный лимит не может быть отрицательным, а у вас" + creditLimit .
*Фактический результат: Сообщение отсутствует.

# Скриншот
![image](https://github.com/ArtemS27/Java_team_diplom/assets/130216421/57dba628-bb58-4c99-ab32-0eef89c69ced)

# Окружение
* **Операционная система:** Windows 11 Домашняя 22H2 х64
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition) Build #IC-231.8109.175, built on March 28, 2023
* **Java:** OpenJDK 11.0.18

**Comment by NikitkaGordeev** [comment]
В метод CreditAccount добавлено условие: https://github.com/ArtemS27/Java_team_diplom/blob/f3172e7e1bca12d4d43c5ef49d4af29c368b3098/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L26-L30
