### ISSUE TITLE
В сберегательном счете начальный баланс больше максимального баланса

### ISSUE THREAD

**Issue by NikitkaGordeev** [ArtemS27/Java_team_diplom#3]
# Описание
В сберегательном счете начальный баланс не может быть больше значения максимального баланса, нужно исключение.

# Локация дефекта
https://github.com/ArtemS27/Java_team_diplom/blob/7c120f56a14f466be2bbf4b2cb1521cc38a1a067/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32

# Шаги воспроизведения
1. Открыть [проект](https://github.com/ArtemS27/Java_team_diplom/tree/saving) в IDEA.
2. Перейти в класс [SavingAccountTest](https://github.com/ArtemS27/Java_team_diplom/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java).
3. Заполнить тест _dontShouldExceedMaxBalance_ значениями:
initialBalance: 100_000;
minBalance: 1_000;
maxBalance: 10_000;
rate: 5; 
4. Сравнить ожидаемый результат с актуальным запустив тест;

*Ожидаемый результат: Выброс исключения: "Начальный баланс не может быть больше максимального баланса".
*Фактический результат: Исключение не выброшено.
# Тест
https://github.com/ArtemS27/Java_team_diplom/blob/7c120f56a14f466be2bbf4b2cb1521cc38a1a067/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L15-L20

# Скриншот
![image](https://github.com/ArtemS27/Java_team_diplom/assets/130284238/c3e663d7-cf6e-4d9d-aaf8-d3f670729432)

# Окружение
* **Операционная система:** Windows 10 Version 22H2 x64
* **IDE:**IntelliJ IDEA 2022.3.3 (Community Edition) Build #IC-223.8836.41, built on March 10, 2023
* **Java:** OpenJDK  "19.0.2" 2023-01-17

**Comment by ArtemS27** [comment]
Добавлено условие выброса исключения при начальном балансе выше максимального баланса.
