### ISSUE TITLE
В сберегательном счете после оплаты баланс может принимать значение меньше минимального баланса

### ISSUE THREAD

**Issue by NikitkaGordeev** [ArtemS27/Java_team_diplom#8]
# Описание
В сберегательном счете после покупки баланс не должен быть меньше минимального баланса, нужно условие.

# Локация дефекта
https://github.com/ArtemS27/Java_team_diplom/blob/7c120f56a14f466be2bbf4b2cb1521cc38a1a067/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L43-L54

# Шаги воспроизведения
1. Открыть [проект](https://github.com/ArtemS27/Java_team_diplom/tree/saving) в IDEA.
2. Перейти в класс [SavingAccountTest](https://github.com/ArtemS27/Java_team_diplom/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java).
3. Заполнить тест _paymentShouldNotThrough_ значениями:
initialBalance: 3_000;
minBalance: 1_000;
maxBalance: 10_000;
rate: 5; 
account.pay: 3_000;
4. Сравнить ожидаемый результат с актуальным запустив тест;

*Ожидаемый результат: Баланс не изменился так как списания не произошло.
*Фактический результат: Произошло списание, баланс меньше значения минимального баланса.
# Тест
https://github.com/ArtemS27/Java_team_diplom/blob/5759c80cd33c02a7e145f7b6dd84128ff51e08e2/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L69-L80

# Скриншот
![image](https://github.com/ArtemS27/Java_team_diplom/assets/130284238/1a0d8827-38e3-4394-9d8e-dff4464ccd85)

# Окружение
* **Операционная система:** Windows 10 Version 22H2 x64
* **IDE:**IntelliJ IDEA 2022.3.3 (Community Edition) Build #IC-223.8836.41, built on March 10, 2023
* **Java:** OpenJDK  "19.0.2" 2023-01-17

**Comment by ArtemS27** [comment]
Изменено условие и формула оплаты.
