### ISSUE TITLE
В сберегательном счете не пополняется баланс если сумма баланса после пополнения равна максимальному балансу

### ISSUE THREAD

**Issue by NikitkaGordeev** [ArtemS27/Java_team_diplom#9]
# Описание
В сберегательном счете после пополнения баланса до максимального значения, баланс не пополняется, нужно условие.

# Локация дефекта
https://github.com/ArtemS27/Java_team_diplom/blob/7c120f56a14f466be2bbf4b2cb1521cc38a1a067/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L67-L78

# Шаги воспроизведения
1. Открыть [проект](https://github.com/ArtemS27/Java_team_diplom/tree/saving) в IDEA.
2. Перейти в класс [SavingAccountTest](https://github.com/ArtemS27/Java_team_diplom/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java).
3. Заполнить тест _shouldReplenishToMaxBalance_ значениями:
initialBalance: 2_000;
minBalance: 1_000;
maxBalance: 5_000;
rate: 5; 
account.add: 3_000;
4. Сравнить ожидаемый результат с актуальным запустив тест;

*Ожидаемый результат: Баланс успешно пополнен. Баланс равен максимальному балансу.
*Фактический результат: Баланс остался прежним, пополнение не произошло.
# Тест
https://github.com/ArtemS27/Java_team_diplom/blob/5759c80cd33c02a7e145f7b6dd84128ff51e08e2/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L129-L139

# Скриншот
![image](https://github.com/ArtemS27/Java_team_diplom/assets/130284238/b7ce86a4-2ccb-4771-811d-b1cd97d187fe)

# Окружение
* **Операционная система:** Windows 10 Version 22H2 x64
* **IDE:**IntelliJ IDEA 2022.3.3 (Community Edition) Build #IC-223.8836.41, built on March 10, 2023
* **Java:** OpenJDK  "19.0.2" 2023-01-17

**Comment by ArtemS27** [comment]
Изменена формула добавление денег на счет.
